### ISSUE TITLE
Prototype audio player roadmap

### ISSUE THREAD

**Issue by fibremint** [fibremint/cirrus#1]
**Roadmap: audio player core**
- [x] Request audio source to server
- [x] Set audio playback service structure based on `cpal-rs`
- [x] Transform audio data binary that in response from server to PCM vector
- [x] Get audio data partially and fill into buffer
- [x] Run audio play and buffer fill function concurrently
- [x] Play and pause audio stream without call `thread::sleep()`
