### ISSUE TITLE
Transcode audio samples

### ISSUE THREAD

**Issue by fibremint** [fibremint/cirrus#29]
**To-do list**
- [x] Encode & decode PCM sample frames with Opus
- [x] Wrap an encoded audio sample frames as packet
- [x] Play audio from Opus packets
